type Translations = readonly [string, string, string, string, string, string, string, string];

export const analyticsTranslations: Record<string, Translations> = {
  "yes": ["ya", "是", "はい", "예", "sim", "ஆம்", "sí", "oui"],
  "no": ["tidak", "否", "いいえ", "아니요", "não", "இல்லை", "no", "non"],
  "Sparse movement cluster": ["Kelompok pergerakan jarang", "稀疏活动聚类", "移動データが少ないクラスター", "이동 기록이 적은 군집", "Grupo com poucos movimentos", "குறைந்த நகர்வுப் பதிவுகளின் குழுமம்", "Grupo con pocos movimientos", "Groupe avec peu de déplacements"],
  "Unlabelled cluster": ["Kelompok tanpa label", "未标记聚类", "ラベルなしのクラスター", "라벨 없는 군집", "Grupo sem rótulo", "பெயரிடப்படாத குழுமம்", "Grupo sin etiqueta", "Groupe sans étiquette"],
  "{profiles} focused-route cluster": ["Kelompok laluan tertumpu: {profiles}", "{profiles}集中路线聚类", "{profiles}の集中ルートクラスター", "{profiles} 집중 경로 군집", "Grupo de rotas focadas: {profiles}", "{profiles} சார்ந்த ஒருமுகப் பாதைக் குழுமம்", "Grupo de rutas concentradas: {profiles}", "Groupe de trajets ciblés : {profiles}"],
  "{profiles} varied-route cluster": ["Kelompok laluan pelbagai: {profiles}", "{profiles}多样路线聚类", "{profiles}の多様なルートクラスター", "{profiles} 다양한 경로 군집", "Grupo de rotas variadas: {profiles}", "{profiles} சார்ந்த பலவகைப் பாதைக் குழுமம்", "Grupo de rutas variadas: {profiles}", "Groupe de trajets variés : {profiles}"],
  "Feature extraction: cultural={cultural}, nature={nature}, urban={urban}, total={total}": ["Pengekstrakan ciri: budaya={cultural}, alam={nature}, bandar={urban}, jumlah={total}", "特征提取：文化={cultural}，自然={nature}，城市={urban}，总计={total}", "特徴抽出：文化={cultural}、自然={nature}、都市={urban}、合計={total}", "특성 추출: 문화={cultural}, 자연={nature}, 도시={urban}, 합계={total}", "Extração de características: cultura={cultural}, natureza={nature}, urbano={urban}, total={total}", "பண்புப் பிரித்தெடுப்பு: கலாசாரம்={cultural}, இயற்கை={nature}, நகரம்={urban}, மொத்தம்={total}", "Extracción de características: cultura={cultural}, naturaleza={nature}, urbano={urban}, total={total}", "Extraction des caractéristiques : culture={cultural}, nature={nature}, urbain={urban}, total={total}"],
  "Rule 1: total matched destination points >= 2 -> {answer}": ["Peraturan 1: jumlah titik destinasi sepadan >= 2 -> {answer}", "规则 1：匹配地点的定位点总数 >= 2 -> {answer}", "ルール1：目的地に一致したポイント数 >= 2 -> {answer}", "규칙 1: 목적지와 일치한 지점 합계 >= 2 -> {answer}", "Regra 1: total de pontos correspondentes a destinos >= 2 -> {answer}", "விதி 1: இடங்களுடன் பொருந்தும் மொத்தப் புள்ளிகள் >= 2 -> {answer}", "Regla 1: total de puntos coincidentes con destinos >= 2 -> {answer}", "Règle 1 : total des points correspondant à des lieux >= 2 -> {answer}"],
  "Rule 2: top interest share >= 55% -> {answer} ({percent}%)": ["Peraturan 2: bahagian minat tertinggi >= 55% -> {answer} ({percent}%)", "规则 2：首要兴趣占比 >= 55% -> {answer}（{percent}%）", "ルール2：最大の関心の割合 >= 55% -> {answer}（{percent}%）", "규칙 2: 가장 높은 관심 비율 >= 55% -> {answer} ({percent}%)", "Regra 2: maior proporção de interesse >= 55% -> {answer} ({percent}%)", "விதி 2: முதன்மை விருப்பத்தின் பங்கு >= 55% -> {answer} ({percent}%)", "Regla 2: proporción del interés principal >= 55% -> {answer} ({percent}%)", "Règle 2 : part de l'intérêt principal >= 55% -> {answer} ({percent}%)"],
  "Rule 3: strongest branch is nature/coastal -> {answer}": ["Peraturan 3: cabang terkuat ialah alam/pantai -> {answer}", "规则 3：最强分支为自然/海滨 -> {answer}", "ルール3：最も強い分岐は自然・海岸 -> {answer}", "규칙 3: 가장 강한 분기는 자연/해안 -> {answer}", "Regra 3: ramo mais forte é natureza/costa -> {answer}", "விதி 3: வலுவான கிளை இயற்கை/கடற்கரை -> {answer}", "Regla 3: la rama más fuerte es naturaleza/costa -> {answer}", "Règle 3 : la branche principale est nature/littoral -> {answer}"],
  "Rule 4: strongest branch is cultural/heritage -> {answer}": ["Peraturan 4: cabang terkuat ialah budaya/warisan -> {answer}", "规则 4：最强分支为文化/历史遗产 -> {answer}", "ルール4：最も強い分岐は文化・歴史遺産 -> {answer}", "규칙 4: 가장 강한 분기는 문화/유산 -> {answer}", "Regra 4: ramo mais forte é cultura/património -> {answer}", "விதி 4: வலுவான கிளை கலாசாரம்/பாரம்பரியம் -> {answer}", "Regla 4: la rama más fuerte es cultura/patrimonio -> {answer}", "Règle 4 : la branche principale est culture/patrimoine -> {answer}"],
  "Rule 5: strongest branch is urban/food -> {answer}": ["Peraturan 5: cabang terkuat ialah bandar/makanan -> {answer}", "规则 5：最强分支为城市/美食 -> {answer}", "ルール5：最も強い分岐は都市・グルメ -> {answer}", "규칙 5: 가장 강한 분기는 도시/음식 -> {answer}", "Regra 5: ramo mais forte é urbano/gastronomia -> {answer}", "விதி 5: வலுவான கிளை நகரம்/உணவு -> {answer}", "Regla 5: la rama más fuerte es urbano/gastronomía -> {answer}", "Règle 5 : la branche principale est urbain/gastronomie -> {answer}"],
  "Rule 6: diversity count >= 2 -> {answer}": ["Peraturan 6: bilangan kategori berbeza >= 2 -> {answer}", "规则 6：类别多样性数量 >= 2 -> {answer}", "ルール6：異なるカテゴリー数 >= 2 -> {answer}", "규칙 6: 서로 다른 범주 수 >= 2 -> {answer}", "Regra 6: número de categorias diferentes >= 2 -> {answer}", "விதி 6: வெவ்வேறு வகைகளின் எண்ணிக்கை >= 2 -> {answer}", "Regla 6: número de categorías diferentes >= 2 -> {answer}", "Règle 6 : nombre de catégories différentes >= 2 -> {answer}"],
  "Leaf: mixed because the route has too little destination evidence.": ["Hasil: bercampur kerana bukti destinasi laluan terlalu sedikit.", "叶节点：地点证据不足，归为混合型。", "結果：目的地のデータが少ないため混合型です。", "결과: 목적지 근거가 부족하여 혼합형입니다.", "Resultado: misto por haver poucos dados de destinos na rota.", "முடிவு: பாதையில் இடங்களின் ஆதாரம் குறைவாக இருப்பதால் கலப்பு வகை.", "Resultado: mixto por haber pocos datos de destinos en la ruta.", "Résultat : mixte, car les données de lieux sont insuffisantes."],
  "Leaf: mixed because movement is spread across multiple attraction groups.": ["Hasil: bercampur kerana pergerakan merangkumi beberapa kumpulan tarikan.", "叶节点：活动分布于多个景点类别，归为混合型。", "結果：複数の観光カテゴリーに移動が分散しているため混合型です。", "결과: 여러 관광지 범주에 이동이 분산되어 혼합형입니다.", "Resultado: misto porque os movimentos abrangem vários grupos de atrações.", "முடிவு: பல சுற்றுலா வகைகளில் நகர்வு பரவியுள்ளதால் கலப்பு வகை.", "Resultado: mixto porque el movimiento abarca varios grupos de atracciones.", "Résultat : mixte, car les déplacements couvrent plusieurs catégories de lieux."],
  "Leaf: nature profile because nature/coastal visits dominate the route.": ["Hasil: alam kerana lawatan alam/pantai mendominasi laluan.", "叶节点：自然/海滨游览占主导，归为自然型。", "結果：自然・海岸への訪問が多いため自然型です。", "결과: 자연/해안 방문이 우세하여 자연형입니다.", "Resultado: natureza porque predominam visitas à natureza e costa.", "முடிவு: இயற்கை/கடற்கரை வருகைகள் அதிகம் உள்ளதால் இயற்கை வகை.", "Resultado: naturaleza porque predominan las visitas a naturaleza y costa.", "Résultat : nature, car les visites de sites naturels et du littoral dominent."],
  "Leaf: cultural profile because cultural/heritage visits dominate the route.": ["Hasil: budaya kerana lawatan budaya/warisan mendominasi laluan.", "叶节点：文化/历史遗产游览占主导，归为文化型。", "結果：文化・歴史遺産への訪問が多いため文化型です。", "결과: 문화/유산 방문이 우세하여 문화형입니다.", "Resultado: cultura porque predominam visitas culturais e patrimoniais.", "முடிவு: கலாசார/பாரம்பரிய வருகைகள் அதிகம் உள்ளதால் கலாசார வகை.", "Resultado: cultura porque predominan las visitas culturales y patrimoniales.", "Résultat : culture, car les visites culturelles et patrimoniales dominent."],
  "Leaf: urban profile because urban/food visits dominate the route.": ["Hasil: bandar kerana lawatan bandar/makanan mendominasi laluan.", "叶节点：城市/美食游览占主导，归为城市型。", "結果：都市・グルメへの訪問が多いため都市型です。", "결과: 도시/음식 방문이 우세하여 도시형입니다.", "Resultado: urbano porque predominam visitas urbanas e gastronómicas.", "முடிவு: நகரம்/உணவு வருகைகள் அதிகம் உள்ளதால் நகர வகை.", "Resultado: urbano porque predominan las visitas urbanas y gastronómicas.", "Résultat : urbain, car les visites urbaines et gastronomiques dominent."],
  "Leaf: mixed because no single branch is decisive after tie-breaking.": ["Hasil: bercampur kerana tiada cabang tunggal yang menentukan selepas pemecahan seri.", "叶节点：平局处理后仍无决定性分支，归为混合型。", "結果：同点の処理後も決定的な分岐がないため混合型です。", "결과: 동률 처리 후에도 결정적인 분기가 없어 혼합형입니다.", "Resultado: misto porque nenhum ramo é decisivo após o desempate.", "முடிவு: சமநிலையைத் தீர்த்த பின்னரும் எந்தக் கிளையும் தீர்மானிக்காததால் கலப்பு வகை.", "Resultado: mixto porque ninguna rama es decisiva tras el desempate.", "Résultat : mixte, car aucune branche n'est décisive après départage."],
  "Leaf: mixed because the tree could not identify a strong travel preference.": ["Hasil: bercampur kerana pepohon tidak mengenal pasti pilihan perjalanan yang kuat.", "叶节点：决策树未识别到明显旅行偏好，归为混合型。", "結果：決定木で明確な旅行の好みを特定できないため混合型です。", "결과: 결정 트리에서 뚜렷한 여행 선호를 찾지 못해 혼합형입니다.", "Resultado: misto porque a árvore não identificou uma preferência forte.", "முடிவு: மரம் வலுவான பயண விருப்பத்தைக் கண்டறியாததால் கலப்பு வகை.", "Resultado: mixto porque el árbol no identificó una preferencia fuerte.", "Résultat : mixte, car l'arbre n'a pas identifié de préférence marquée."],
};
