import type { Locale } from "./i18n";

const english = {
  location: "Explore around",
  current: "My current location",
  area: "Choose an area",
  choose: "Select an area",
  chooseState: "Select a state",
  privacy: "Browse without sharing GPS. This choice does not record a trip or a visit.",
  fromArea: "From the selected area centre",
  centreArea: "Centre on selected area",
  nearby: "A place nearby",
  popular: "A popular stop in recorded routes",
  preference: "A nearby place for your travel style",
  view: "View place",
  hide: "Don't recommend this place",
  dismiss: "Close",
  settings: "Settings",
  announcements: "Upcoming event announcements",
  event: "An event in this area",
  viewEvent: "View event calendar",
  hidden: "Hidden recommendations",
  restore: "Restore hidden places",
  noLocal: "No places in this area yet. Try another nearby area.",
  distance: "km away",
  locationNeeded: "Allow location or choose an area to see local suggestions.",
  eventsInArea: "Events in the selected area",
};

export type DiscoveryCopyKey = keyof typeof english;
const copy: Record<Locale, Record<DiscoveryCopyKey, string>> = {
  en: english,
  ms: {
    chooseState: "Pilih negeri",
    eventsInArea: "Acara di kawasan pilihan",
    location: "Terokai sekitar", current: "Lokasi semasa saya", area: "Pilih kawasan", choose: "Pilih kawasan",
    privacy: "Terokai tanpa berkongsi GPS. Pilihan ini tidak merekodkan perjalanan atau lawatan.",
    fromArea: "Dari pusat kawasan pilihan", centreArea: "Pusatkan pada kawasan pilihan",
    nearby: "Tempat berdekatan", popular: "Persinggahan popular dalam laluan yang direkodkan", preference: "Tempat berdekatan yang sesuai dengan gaya perjalanan anda",
    view: "Lihat tempat", hide: "Jangan cadangkan tempat ini", dismiss: "Tutup", settings: "Tetapan",
    announcements: "Pengumuman acara akan datang", event: "Acara di kawasan ini", viewEvent: "Lihat kalendar acara",
    hidden: "Cadangan tersembunyi", restore: "Pulihkan tempat tersembunyi", noLocal: "Belum ada tempat di kawasan ini. Cuba kawasan berdekatan yang lain.",
    distance: "km dari sini", locationNeeded: "Benarkan lokasi atau pilih kawasan untuk melihat cadangan setempat.",
  },
  zh: {
    chooseState: "选择州",
    eventsInArea: "所选地区的活动",
    location: "探索周边", current: "我的当前位置", area: "选择地区", choose: "选择地区",
    privacy: "无需共享 GPS 即可浏览。此选择不会记录行程或到访。", fromArea: "距所选地区中心", centreArea: "回到所选地区",
    nearby: "附近的地点", popular: "已记录路线中的热门停留地点", preference: "附近适合您旅行偏好的地点",
    view: "查看地点", hide: "不再推荐此地点", dismiss: "关闭", settings: "设置", announcements: "即将举行的活动通知",
    event: "此地区的活动", viewEvent: "查看活动日历", hidden: "已隐藏的推荐", restore: "恢复已隐藏的地点",
    noLocal: "此地区暂无地点。请尝试其他附近地区。", distance: "公里外", locationNeeded: "允许定位或选择地区以查看当地推荐。",
  },
  ja: {
    chooseState: "州を選択",
    eventsInArea: "選択したエリアのイベント",
    location: "周辺を探す", current: "現在地", area: "エリアを選ぶ", choose: "エリアを選択",
    privacy: "GPSを共有せずに閲覧できます。この選択では旅行や訪問は記録されません。", fromArea: "選択したエリアの中心から", centreArea: "選択したエリアに戻る",
    nearby: "近くのスポット", popular: "記録されたルートで人気の立ち寄り先", preference: "旅行の好みに合う近くのスポット",
    view: "スポットを見る", hide: "このスポットをおすすめしない", dismiss: "閉じる", settings: "設定", announcements: "今後のイベントのお知らせ",
    event: "このエリアのイベント", viewEvent: "イベントカレンダーを見る", hidden: "非表示のおすすめ", restore: "非表示のスポットを戻す",
    noLocal: "このエリアにはまだスポットがありません。近くの別のエリアをお試しください。", distance: "km先", locationNeeded: "位置情報を許可するか、エリアを選んで周辺のおすすめをご覧ください。",
  },
  ko: {
    chooseState: "주 선택",
    eventsInArea: "선택한 지역의 행사",
    location: "주변 둘러보기", current: "내 현재 위치", area: "지역 선택", choose: "지역 선택",
    privacy: "GPS를 공유하지 않고 둘러볼 수 있습니다. 이 선택은 여행이나 방문을 기록하지 않습니다.", fromArea: "선택한 지역 중심에서", centreArea: "선택한 지역으로 돌아가기",
    nearby: "가까운 장소", popular: "기록된 경로에서 인기 있는 방문지", preference: "여행 취향에 맞는 가까운 장소",
    view: "장소 보기", hide: "이 장소 추천하지 않기", dismiss: "닫기", settings: "설정", announcements: "예정된 행사 알림",
    event: "이 지역의 행사", viewEvent: "행사 달력 보기", hidden: "숨긴 추천", restore: "숨긴 장소 복원",
    noLocal: "이 지역에는 아직 장소가 없습니다. 다른 가까운 지역을 선택해 주세요.", distance: "km 거리", locationNeeded: "위치를 허용하거나 지역을 선택하여 주변 추천을 확인하세요.",
  },
  pt: {
    chooseState: "Selecionar um estado",
    eventsInArea: "Eventos na área selecionada",
    location: "Explorar nas proximidades", current: "Minha localização atual", area: "Escolher uma área", choose: "Selecionar uma área",
    privacy: "Explore sem compartilhar o GPS. Esta escolha não registra viagens nem visitas.", fromArea: "Do centro da área selecionada", centreArea: "Centrar na área selecionada",
    nearby: "Um lugar próximo", popular: "Uma parada popular nas rotas registradas", preference: "Um lugar próximo para seu estilo de viagem",
    view: "Ver lugar", hide: "Não recomendar este lugar", dismiss: "Fechar", settings: "Configurações", announcements: "Avisos de próximos eventos",
    event: "Um evento nesta área", viewEvent: "Ver calendário de eventos", hidden: "Recomendações ocultas", restore: "Restaurar lugares ocultos",
    noLocal: "Ainda não há lugares nesta área. Tente outra área próxima.", distance: "km de distância", locationNeeded: "Permita a localização ou escolha uma área para ver sugestões locais.",
  },
  ta: {
    chooseState: "மாநிலத்தைத் தேர்ந்தெடுக்கவும்",
    eventsInArea: "தேர்ந்தெடுத்த பகுதியில் நிகழ்வுகள்",
    location: "அருகில் ஆராயுங்கள்", current: "எனது தற்போதைய இடம்", area: "ஒரு பகுதியைத் தேர்ந்தெடுக்கவும்", choose: "பகுதியைத் தேர்ந்தெடுக்கவும்",
    privacy: "GPS பகிராமல் பார்க்கலாம். இந்தத் தேர்வு பயணத்தையோ வருகையையோ பதிவு செய்யாது.", fromArea: "தேர்ந்தெடுத்த பகுதியின் மையத்திலிருந்து", centreArea: "தேர்ந்தெடுத்த பகுதிக்குத் திரும்பவும்",
    nearby: "அருகிலுள்ள ஓர் இடம்", popular: "பதிவுசெய்யப்பட்ட வழித்தடங்களில் பிரபலமான இடம்", preference: "உங்கள் பயண விருப்பத்திற்கேற்ற அருகிலுள்ள இடம்",
    view: "இடத்தைப் பார்க்கவும்", hide: "இந்த இடத்தைப் பரிந்துரைக்க வேண்டாம்", dismiss: "மூடு", settings: "அமைப்புகள்", announcements: "வரவிருக்கும் நிகழ்வு அறிவிப்புகள்",
    event: "இந்தப் பகுதியில் ஒரு நிகழ்வு", viewEvent: "நிகழ்வு நாட்காட்டியைப் பார்க்கவும்", hidden: "மறைக்கப்பட்ட பரிந்துரைகள்", restore: "மறைக்கப்பட்ட இடங்களை மீட்டெடுக்கவும்",
    noLocal: "இந்தப் பகுதியில் இன்னும் இடங்கள் இல்லை. அருகிலுள்ள வேறு பகுதியை முயற்சிக்கவும்.", distance: "கி.மீ தொலைவில்", locationNeeded: "உள்ளூர் பரிந்துரைகளைப் பார்க்க இருப்பிடத்தை அனுமதிக்கவும் அல்லது பகுதியைத் தேர்ந்தெடுக்கவும்.",
  },
  es: {
    chooseState: "Seleccionar un estado",
    eventsInArea: "Eventos en la zona elegida",
    location: "Explorar alrededor de", current: "Mi ubicación actual", area: "Elegir una zona", choose: "Seleccionar una zona",
    privacy: "Explora sin compartir el GPS. Esta elección no registra viajes ni visitas.", fromArea: "Desde el centro de la zona elegida", centreArea: "Centrar en la zona elegida",
    nearby: "Un lugar cercano", popular: "Una parada popular en las rutas registradas", preference: "Un lugar cercano para tu estilo de viaje",
    view: "Ver lugar", hide: "No recomendar este lugar", dismiss: "Cerrar", settings: "Ajustes", announcements: "Avisos de próximos eventos",
    event: "Un evento en esta zona", viewEvent: "Ver calendario de eventos", hidden: "Recomendaciones ocultas", restore: "Restaurar lugares ocultos",
    noLocal: "Todavía no hay lugares en esta zona. Prueba otra zona cercana.", distance: "km de distancia", locationNeeded: "Permite la ubicación o elige una zona para ver sugerencias locales.",
  },
  fr: {
    chooseState: "Sélectionner un État",
    eventsInArea: "Événements dans la zone choisie",
    location: "Explorer autour de", current: "Ma position actuelle", area: "Choisir une zone", choose: "Sélectionner une zone",
    privacy: "Explorez sans partager votre GPS. Ce choix n'enregistre ni trajet ni visite.", fromArea: "Depuis le centre de la zone choisie", centreArea: "Recentrer sur la zone choisie",
    nearby: "Un lieu à proximité", popular: "Une halte populaire dans les itinéraires enregistrés", preference: "Un lieu proche adapté à vos goûts",
    view: "Voir le lieu", hide: "Ne plus recommander ce lieu", dismiss: "Fermer", settings: "Paramètres", announcements: "Annonces des prochains événements",
    event: "Un événement dans cette région", viewEvent: "Voir le calendrier des événements", hidden: "Recommandations masquées", restore: "Restaurer les lieux masqués",
    noLocal: "Aucun lieu dans cette zone pour le moment. Essayez une autre zone proche.", distance: "km de distance", locationNeeded: "Autorisez la localisation ou choisissez une zone pour voir les suggestions locales.",
  },
};

export function discoveryText(locale: Locale, key: DiscoveryCopyKey) {
  return copy[locale][key];
}
