type Translations = readonly [string, string, string, string, string, string, string, string];

export const safetyNoticeTranslations: Record<string, Translations> = {
  "KLCC crowd watch zone": ["Zon pantauan kesesakan KLCC", "KLCC 人流监测区", "KLCC混雑監視エリア", "KLCC 혼잡 관찰 구역", "Zona de afluência KLCC", "KLCC கூட்டக் கண்காணிப்புப் பகுதி", "Zona de afluencia KLCC", "Zone de fréquentation KLCC"],
  "George Town heritage walk zone": ["Zon berjalan kaki warisan George Town", "George Town 历史步行区", "George Town歴史地区の徒歩エリア", "George Town 역사 도보 구역", "Zona histórica pedonal de George Town", "George Town பாரம்பரிய நடைப் பகுதி", "Zona histórica peatonal de George Town", "Zone de promenade historique de George Town"],
  "Batu Caves festival crowd zone": ["Zon kesesakan perayaan Batu Caves", "Batu Caves 节庆人流区", "Batu Caves祭りの混雑エリア", "Batu Caves 축제 혼잡 구역", "Zona de afluência festiva de Batu Caves", "Batu Caves திருவிழாக் கூட்டப் பகுதி", "Zona de afluencia festiva de Batu Caves", "Zone de fréquentation festive de Batu Caves"],
  "Jonker Street evening crowd zone": ["Zon kesesakan petang Jonker Street", "Jonker Street 晚间人流区", "Jonker Street夕方の混雑エリア", "Jonker Street 저녁 혼잡 구역", "Zona de afluência noturna de Jonker Street", "Jonker Street மாலை கூட்டப் பகுதி", "Zona de afluencia nocturna de Jonker Street", "Zone de fréquentation en soirée de Jonker Street"],
  "Tanjung Aru sunset crowd zone": ["Zon kesesakan matahari terbenam Tanjung Aru", "Tanjung Aru 日落人流区", "Tanjung Aru夕日の混雑エリア", "Tanjung Aru 일몰 혼잡 구역", "Zona de afluência ao pôr do sol de Tanjung Aru", "Tanjung Aru சூரிய அஸ்தமனக் கூட்டப் பகுதி", "Zona de afluencia al atardecer de Tanjung Aru", "Zone de fréquentation au coucher du soleil de Tanjung Aru"],
  "KLCC is receiving stronger visitor movement right now.": ["KLCC sedang menerima lebih banyak pergerakan pengunjung.", "KLCC 当前游客活动较多。", "KLCCでは現在、訪問者の移動が増えています。", "현재 KLCC 방문객 이동이 증가하고 있습니다.", "O KLCC está a receber mais movimento de visitantes.", "KLCC இல் தற்போது பார்வையாளர் நகர்வு அதிகமாக உள்ளது.", "KLCC está recibiendo más movimiento de visitantes.", "Le KLCC connaît actuellement davantage de déplacements de visiteurs."],
  "Expect busier walkways and consider nearby alternatives if you prefer a quieter stop.": ["Jangka laluan lebih sibuk; pilih alternatif berdekatan jika mahu tempat tenang.", "步行道可能较繁忙，如偏好安静，可考虑附近替代地点。", "歩道の混雑が予想されます。静かな場所を希望する場合は近くの別の場所を検討してください。", "보행로가 붐빌 수 있습니다. 조용한 장소를 원하면 근처 대안을 고려하세요.", "Espere passeios mais movimentados e considere alternativas próximas se preferir tranquilidade.", "நடைப்பாதைகளில் கூட்டம் அதிகமாகலாம்; அமைதி விரும்பினால் அருகிலுள்ள மாற்று இடங்களைக் கருதவும்.", "Espere aceras concurridas y considere alternativas cercanas si prefiere tranquilidad.", "Attendez-vous à des allées fréquentées et envisagez des alternatives proches pour plus de calme."],
  "You are near a monitored heritage walking area.": ["Anda berhampiran kawasan berjalan kaki warisan yang dipantau.", "您在受监测的历史步行区附近。", "監視対象の歴史地区の徒歩エリアに近づいています。", "모니터링되는 역사 도보 구역 근처에 있습니다.", "Está perto de uma zona histórica pedonal monitorizada.", "கண்காணிக்கப்படும் பாரம்பரிய நடைப் பகுதிக்கு அருகில் உள்ளீர்கள்.", "Está cerca de una zona histórica peatonal monitorizada.", "Vous êtes près d'une zone de promenade historique suivie."],
  "Use check-in when you arrive at a specific attraction so your visit duration is recorded.": ["Daftar masuk apabila tiba di tarikan supaya tempoh lawatan direkodkan.", "到达景点时请签到，以记录游览时长。", "観光地に到着したらチェックインすると滞在時間を記録できます。", "명소에 도착하면 체크인하여 방문 시간을 기록하세요.", "Registe a chegada à atração para guardar a duração da visita.", "வருகை நேரத்தைப் பதிவு செய்யச் சுற்றுலா இடத்தை அடைந்ததும் வருகைப் பதிவு செய்யவும்.", "Registre la llegada a la atracción para guardar la duración de la visita.", "Enregistrez votre arrivée à l'attraction pour conserver la durée de la visite."],
  "Batu Caves can become crowded during cultural and religious periods.": ["Batu Caves boleh sesak semasa perayaan budaya dan agama.", "文化和宗教节庆期间，Batu Caves 可能较拥挤。", "文化行事や宗教行事の期間はBatu Cavesが混雑することがあります。", "문화 및 종교 행사 기간에 Batu Caves가 붐빌 수 있습니다.", "Batu Caves pode encher durante períodos culturais e religiosos.", "கலாச்சார மற்றும் சமய விழாக்களில் Batu Caves இல் கூட்டம் அதிகமாகலாம்.", "Batu Caves puede llenarse durante celebraciones culturales y religiosas.", "Batu Caves peut être bondé pendant les célébrations culturelles et religieuses."],
  "Plan extra time for steps, queues, and transport around the entrance area.": ["Sediakan masa tambahan untuk tangga, barisan dan pengangkutan sekitar pintu masuk.", "请为台阶、排队和入口附近交通预留更多时间。", "階段、行列、入口付近の移動には余裕を持たせてください。", "계단, 대기줄, 입구 주변 교통에 여유 시간을 두세요.", "Reserve tempo extra para escadas, filas e transportes junto à entrada.", "படிகள், வரிசைகள் மற்றும் நுழைவுப் பகுதி போக்குவரத்துக்கு கூடுதல் நேரம் ஒதுக்கவும்.", "Reserve más tiempo para escaleras, colas y transporte cerca de la entrada.", "Prévoyez plus de temps pour les escaliers, files et transports près de l'entrée."],
  "Jonker Street has a higher chance of crowding around evening market hours.": ["Jonker Street lebih berkemungkinan sesak semasa pasar petang.", "夜市时段 Jonker Street 更容易拥挤。", "夕方の市場の時間帯はJonker Streetが混雑しやすくなります。", "저녁 시장 시간에는 Jonker Street가 더 붐빌 수 있습니다.", "Jonker Street tem maior probabilidade de encher durante o mercado noturno.", "மாலை சந்தை நேரங்களில் Jonker Street இல் கூட்டம் அதிகமாக வாய்ப்புள்ளது.", "Jonker Street tiene más probabilidad de llenarse durante el mercado nocturno.", "Jonker Street risque davantage d'être bondé aux heures du marché du soir."],
  "Keep belongings close and use the app's incident report if something goes wrong.": ["Jaga barang anda dan gunakan laporan insiden aplikasi jika berlaku masalah.", "请看管好随身物品；如遇问题，可使用应用的事件报告。", "持ち物を身近に置き、問題が起きたらアプリから報告してください。", "소지품을 가까이 두고 문제가 생기면 앱에서 사건을 신고하세요.", "Guarde os pertences perto de si e relate incidentes na aplicação se necessário.", "உடைமைகளை அருகில் வைத்திருந்து சிக்கல் ஏற்பட்டால் செயலியில் சம்பவ அறிக்கை செய்யவும்.", "Mantenga sus pertenencias cerca y use el informe de incidentes de la aplicación si es necesario.", "Gardez vos affaires près de vous et utilisez le signalement dans l'application en cas de problème."],
  "Sunset hours can bring heavier movement around Tanjung Aru Beach.": ["Waktu matahari terbenam boleh meningkatkan pergerakan sekitar Pantai Tanjung Aru.", "日落时 Tanjung Aru Beach 周边活动可能增多。", "夕日の時間にはTanjung Aru Beach付近で移動が増えることがあります。", "일몰 시간에는 Tanjung Aru Beach 주변 이동이 증가할 수 있습니다.", "Ao pôr do sol pode haver mais movimento junto à praia de Tanjung Aru.", "சூரிய அஸ்தமன நேரங்களில் Tanjung Aru Beach அருகே நகர்வு அதிகமாகலாம்.", "Al atardecer puede haber más movimiento cerca de Tanjung Aru Beach.", "Le coucher du soleil peut attirer davantage de visiteurs autour de Tanjung Aru Beach."],
  "Arrive earlier if you want an easier walking route and clearer pickup point.": ["Tiba lebih awal untuk laluan berjalan lebih mudah dan tempat pengambilan lebih jelas.", "早点抵达可获得更顺畅的步行路线和更方便的上车点。", "歩きやすいルートと分かりやすい迎車場所を希望する場合は、早めに到着してください。", "걷기 편한 경로와 찾기 쉬운 승차 지점을 원하면 일찍 도착하세요.", "Chegue mais cedo para caminhar mais facilmente e encontrar um ponto de recolha claro.", "எளிதான நடைப்பாதைக்கும் தெளிவான வாகன ஏற்ற இடத்திற்கும் முன்பே வரவும்.", "Llegue antes para caminar con más facilidad y encontrar un punto de recogida claro.", "Arrivez plus tôt pour marcher plus facilement et trouver un point de prise en charge clair."],
  "{count} m away": ["{count} m jauhnya", "距离 {count} 米", "{count}m先", "{count}m 거리", "A {count} m", "{count} மீட்டர் தூரம்", "A {count} m", "À {count} m"],
  "Police contact in the prepared directory.": ["Hubungan polis dalam direktori yang disediakan.", "预设目录中的警务联系点。", "用意された一覧にある警察の連絡先。", "준비된 목록의 경찰 연락처.", "Contacto policial no diretório preparado.", "தயாரிக்கப்பட்ட பட்டியலில் உள்ள காவல் தொடர்பு.", "Contacto policial del directorio preparado.", "Contact de police du répertoire préparé."],
  "Hospital in the prepared directory.": ["Hospital dalam direktori yang disediakan.", "预设目录中的医院。", "用意された一覧にある病院。", "준비된 목록의 병원.", "Hospital no diretório preparado.", "தயாரிக்கப்பட்ட பட்டியலில் உள்ள மருத்துவமனை.", "Hospital del directorio preparado.", "Hôpital du répertoire préparé."],
  "Fire and rescue contact in the prepared directory.": ["Hubungan bomba dan penyelamat dalam direktori yang disediakan.", "预设目录中的消防救援联系点。", "用意された一覧にある消防・救助の連絡先。", "준비된 목록의 소방 및 구조 연락처.", "Contacto de bombeiros e resgate no diretório preparado.", "தயாரிக்கப்பட்ட பட்டியலில் உள்ள தீயணைப்பு மற்றும் மீட்புத் தொடர்பு.", "Contacto de bomberos y rescate del directorio preparado.", "Contact de pompiers et secours du répertoire préparé."],
};
